import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | Waltzing Koala',
    default: 'Waltzing Koala'
  },
  description: 'Waltzing Koala is an event-guidance app for hosts without a DJ or MC. It integrates Spotify playlists and helps organise event timelines with custom announcements generated by OpenAI. Users can manually trigger announcements and seamlessly transition between playlists for a smooth event experience.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
